# Generated by Django 3.2.5 on 2022-05-11 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='name',
            new_name='Course',
        ),
    ]
